# -*- coding: utf-8 -*-
"""CARREGAR_DADOS_CAMADA_RAW.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jO5-iI3XOr6nKQtDLz1QEg1QGMNa7jP9

# CABEÇALHO
* Nome do aluno: Emanuel Godinho Pedrozo
* Matrícula: 1415956 
* Professor: Victor Sales Silva
* Disciplina: PREPARAÇÃO E INGESTÃO DE DADOS
* Atividade: Exercício 3 - ETL & ELT (BATCH)

IMPORTAR AS BIBLIOTECAS
"""

#pip install azure-storage-blob

import requests
import zipfile
from azure.storage.blob import BlobClient
import os
import pandas as pd
import numpy as np

"""CADEIA DE CONEXÃO"""

cadeia_conexao = 'DefaultEndpointsProtocol=https;AccountName=storageaccount1415956;AccountKey=VP3Anbpvb8xOCraYw0fllNTkc9nR/BfbmKObg+J1c+Q+lXkccsa2VZA/IO5Es7sel5HT0zKnIsOj+ASt+V2bqA==;EndpointSuffix=core.windows.net'

"""ENVIAR OS DADOS PARA AZURE STOREGE BLOB"""

arquivo_blob = '/home/azureuser/airflow/arquivos/DADOS_EXAMES.csv'
blob = BlobClient.from_connection_string(conn_str=cadeia_conexao, container_name="datalake-aulas", blob_name='raw/DADOS_EXAMES/DADOS_EXAMES.csv' )
with open(arquivo_blob, "rb") as data:
  blob.upload_blob(data)

