# -*- coding: utf-8 -*-
"""NORMALIZAR_DADOS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rZc0TBYHaZusoQWsBr_WGonSpj2iUIaV

# CABEÇALHO
* Nome do aluno: Emanuel Godinho Pedrozo
* Matrícula: 1415956 
* Professor: Victor Sales Silva
* Disciplina: PREPARAÇÃO E INGESTÃO DE DADOS
* Atividade: Exercício 3 - ETL & ELT (BATCH)

IMPORTAR AS BIBLIOTECAS
"""

#pip install azure-storage-blob

import requests
import zipfile
from azure.storage.blob import BlobClient
import os
import pandas as pd
import numpy as np

"""URL DOS DADOS"""

url_dados_exames = 'https://storageaccount1415956.blob.core.windows.net/datalake-aulas/raw/DADOS_EXAMES/DADOS_EXAMES.csv'

df_url_dados_exames = pd.read_csv(url_dados_exames, sep=';')

df_url_dados_exames.head()

"""AJUSTE DOS SCHEMAS"""

df_url_dados_exames['IdExame'] = df_url_dados_exames['IdExame'].fillna(0)
df_url_dados_exames['QtdExames'] = df_url_dados_exames['QtdExames'].fillna(0)
df_url_dados_exames['QtdAmostrasColhidas'] = df_url_dados_exames['QtdAmostrasColhidas'].fillna(0)
df_url_dados_exames['IdExame'] = df_url_dados_exames['IdExame'].astype(int)
df_url_dados_exames['QtdExames'] = df_url_dados_exames['QtdExames'].astype(int)
df_url_dados_exames['QtdAmostrasColhidas'] = df_url_dados_exames['QtdAmostrasColhidas'].astype(int)
df_url_dados_exames['Cidade'] = df_url_dados_exames['Cidade'].astype('string')
df_url_dados_exames['Estado'] = df_url_dados_exames['Estado'].astype('string')
df_url_dados_exames['NumPedido'] = df_url_dados_exames['NumPedido'].astype('string')
df_url_dados_exames['Exame'] = df_url_dados_exames['Exame'].astype('string')
df_url_dados_exames['SiglaExame'] = df_url_dados_exames['SiglaExame'].astype('string')
df_url_dados_exames['Material'] = df_url_dados_exames['Material'].astype('string')
df_url_dados_exames['SetorExame'] = df_url_dados_exames['SetorExame'].astype('string')
df_url_dados_exames['SetorExame'] = df_url_dados_exames['SetorExame'].astype('string')
df_url_dados_exames['DataPedido'] = df_url_dados_exames['DataPedido'].astype('datetime64')
df_url_dados_exames['DataPrevistaEntregaResultado'] = df_url_dados_exames['DataPrevistaEntregaResultado'].astype('datetime64')
df_url_dados_exames['DataLiberacaoResultado'] = df_url_dados_exames['DataLiberacaoResultado'].astype('datetime64')

"""INSERÇÃO DO CAMPO IDCIDADE"""

df_url_dados_exames['IdCidade'] = np.where(df_url_dados_exames['Cidade']=='BELO HORIZONTE', '1',
                                   np.where(df_url_dados_exames['Cidade']=='CONTAGEM', '2', ''))

"""FAZENDO A ORDENAÇÃO DE TODOS OS CAMPOS"""

df_url_dados_exames[['IdUnidadeAtendimento', 'IdCidade', 'Cidade', 'Estado', 'NumPedido', 'IdExame', 'Exame', 'SiglaExame', 'Material', 'SetorExame', 'PrecoExame', 'DataPedido', 'QtdExames', 'QtdAmostrasColhidas', 'DataPrevistaEntregaResultado', 'DataLiberacaoResultado']]

"""AJUTES DO TIPO DO CAMPO IDCIDADE"""

df_url_dados_exames['IdCidade'] = df_url_dados_exames['IdCidade'].astype('int64')

"""CRIAÇÃO DO DATRAME DIM_CIDADE"""

df_dim_cidades = df_url_dados_exames.loc[:, ['IdCidade', 'Cidade', 'Estado']]

"""REMOÇÃO DAS INFORMAÇÃOES DUPLICADAS"""

df_dim_cidades = df_dim_cidades.drop_duplicates()

"""CRIAÇÃO DO DATAFRAME DIM_EXAME"""

df_dim_exane = df_url_dados_exames.loc[:, ['IdExame', 'Exame', 'SiglaExame', 'Material', 'SetorExame']]

"""REMOÇÃO DOS CAMPO NO df_url_dados_exames"""

df_url_dados_exames = df_url_dados_exames.drop('Cidade', axis=1)
df_url_dados_exames = df_url_dados_exames.drop('Estado', axis=1)
df_url_dados_exames = df_url_dados_exames.drop('Exame', axis=1)
df_url_dados_exames = df_url_dados_exames.drop('SiglaExame', axis=1)
df_url_dados_exames = df_url_dados_exames.drop('Material', axis=1)
df_url_dados_exames = df_url_dados_exames.drop('SetorExame', axis=1)

df_url_dados_exames.head()

"""SALVANDO OS DATAFRAMES EM CVS"""

df_url_dados_exames.to_csv('/home/azureuser/airflow/arquivos/DADOS_EXAMES_NORMALIZADOS.csv', index=False)

df_dim_cidades.to_csv('/home/azureuser/airflow/arquivos/DIM_CIDADES.csv', index=False)

df_dim_exane.to_csv('/home/azureuser/airflow/arquivos/DIM_EXAMES.csv', index=False)